package au.org.auscope.util;

import java.io.File;
import java.io.FileFilter;
import java.io.FileWriter;
import java.net.URI;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

import org.dom4j.Document;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.dom4j.io.OutputFormat;
import org.dom4j.io.SAXReader;
import org.dom4j.io.XMLWriter;

/**
 * Expand an XML Catalog by converting rewriteURI entries into explicit
 * individual uri mappings, to support Eclipse, which does not support rewrites.
 * 
 * <p>
 * 
 * Usage: program input.xml output.xml
 * 
 */
public class XmlCatalogExpander {

    /**
     * @param directory
     * @param filter
     * @return list of files matching filter in directory and its children
     */
    public static List<File> recursiveListFiles(File directory,
            FileFilter filter) {
        List<File> files = new ArrayList<File>();
        for (File f : directory.listFiles()) {
            if (f.isDirectory()) {
                files.addAll(recursiveListFiles(f, filter));
            } else if (filter.accept(f)) {
                files.add(f);
            }
        }
        return files;
    }

    /**
     * All a uri element to outputRootElement for every .xsd file found user the
     * directory named rewritePrefix (relative to catalog file).
     * 
     * @param outputRootElement
     * @param catalogFile
     * @param uriStartString
     * @param rewritePrefix
     * @throws Exception
     */
    public static void addUriElements(Element outputRootElement,
            File catalogFile, String uriStartString, String rewritePrefix)
            throws Exception {
        File catalogDirectory = catalogFile.getParentFile();
        File rewriteDirectory = new File(catalogDirectory.getPath()
                + File.separator + rewritePrefix);
        URI catalogDirectoryUri = catalogDirectory.toURI();
        URI rewriteDirectoryUri = rewriteDirectory.toURI();
        URI baseUri = new URI(uriStartString);

        List<File> files = recursiveListFiles(rewriteDirectory,
                new FileFilter() {
                    public boolean accept(File pathname) {
                        return pathname.getPath().endsWith(".xsd");
                    }
                });
        Collections.sort(files);
        for (File file : files) {
            URI uri = file.toURI();
            Element uriElement = outputRootElement.addElement("uri");
            catalogDirectory.toURI().getPath();
            file.toURI().getPath();
            uriElement.addAttribute("name", baseUri.resolve(
                    rewriteDirectoryUri.relativize(uri)).toString());
            uriElement.addAttribute("uri", catalogDirectoryUri.relativize(uri)
                    .toString());
        }
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            System.err.println("Usage: java -jar XmlCatalogExpander.jar"
                    + " input.xml output.xml");
            System.exit(1);
        }
        File inputFile = new File(args[0]);
        File outputFile = new File(args[1]);
        if (inputFile.equals(outputFile)) {
            throw new RuntimeException("input file same as output file");
        }
        SAXReader saxReader = new SAXReader();
        Document inputDocument = saxReader.read(inputFile);
        Document outputDocument = DocumentHelper.createDocument();
        outputDocument.setDocType(inputDocument.getDocType());
        // FIXME: this doesn't work
        // outputDocument
        // .addComment("This file is automatically generated. Do not edit."
        // + " It contains one uri element for each .xsd"
        // + " so that this catalog can be used by Eclipse,"
        // + " which does not support rewriteURI.");
        Element inputRootElement = inputDocument.getRootElement();
        Element outputRootElement = inputRootElement.createCopy();
        outputRootElement.clearContent();
        outputDocument.setRootElement(outputRootElement);

        for (Iterator<?> i = inputRootElement.elementIterator("rewriteURI"); i
                .hasNext();) {
            Element e = (Element) i.next();
            String uriStartString = e.attributeValue("uriStartString");
            String rewritePrefix = e.attributeValue("rewritePrefix");
            addUriElements(outputRootElement, inputFile, uriStartString,
                    rewritePrefix);
        }

        OutputFormat format = OutputFormat.createPrettyPrint();
        XMLWriter writer = new XMLWriter(new FileWriter(outputFile), format);
        writer.write(outputDocument);
        writer.close();

    }

}
